on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Release
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Semver Release
        uses: K-Phoen/semver-release-action@v1.2.0
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
