on:
    push:
      branches:
          - main
    pull_request:
        branches:
          - main
    workflow_dispatch:

permissions:
    contents: read

env:
    LATEST_GO_VERSION: "1.20"

name: Vulnerability Check
jobs:
    Security:
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v4
              with:
                go-version: ${{ env.LATEST_GO_VERSION }}
                check-latest: true
            - name: Run golint
              run: |
                go install golang.org/x/lint/golint@latest
                golint -set_exit_status ./...
            - name: Run govulncheck
              run: |
                go install golang.org/x/vuln/cmd/govulncheck@latest
                govulncheck ./...